package ie.atu.sw;

public enum Colour {
	ABSOLUTE_ZERO 				("Absolute Zero", 0x0048BA),
	ACID_GREEN 					("Acid Green", 0xB0BF1A),
	AERO 						("Aero", 0x7CB9E8),
	AFRICAN_VIOLET 				("African Violet", 0xB284BE),
	AIR_SUPERIORITY_BLUE 		("Air Superiority Blue", 0x72A0C1),
	ALICE_BLUE 					("Alice Blue", 0xF0F8FF),
	ALIZARIN 					("Alizarin", 0xDB2D43),
	ALLOY_ORANGE 				("Alloy Orange", 0xC46210),
	ALMOND 						("Almond", 0xEFDECD),
	AMARANTH_DEEP_PURPLE 		("Amaranth Deep Purple", 0x9F2B68),
	AMARANTH_PINK 				("Amaranth Pink", 0xF19CBB),
	AMARANTH_PURPLE 			("Amaranth Purple", 0xAB274F),
	AMAZON 						("Amazon", 0x3B7A57),
	AMBER 						("Amber", 0xFFBF00),
	AMETHYST 					("Amethyst", 0x9966CC),
	ANDROID_GREEN 				("Android Green", 0x3DDC84),
	ANTIQUE_BRASS 				("Antique Brass", 0xCD9575),
	ANTIQUE_BRONZE 				("Antique Bronze", 0x665D1E),
	ANTIQUE_FUCHSIA 			("Antique Fuchsia", 0x915C83),
	ANTIQUE_RUBY 				("Antique Ruby", 0x841B2D),
	ANTIQUE_WHITE 				("Antique White", 0xFAEBD7),
	APRICOT 					("Apricot", 0xFBCEB1),
	AQUA 						("Aqua", 0x00FFFF),
	AQUAMARINE 					("Aquamarine", 0x7FFFD4),
	ARCTIC_LIME 				("Arctic Lime", 0xD0FF14),
	ARTICHOKE_GREEN 			("Artichoke Green", 0x4B6F44),
	ARYLIDE_YELLOW 				("Arylide Yellow", 0xE9D66B),
	ASH_GRAY 					("Ash Gray", 0xB2BEB5),
	ATOMIC_TANGERINE 			("Atomic Tangerine", 0xFF9966),
	AUREOLIN 					("Aureolin", 0xFDEE00),
	AZURE 						("Azure", 0x007FFF),
	AZURE_X11_WEB_COLOR 		("Azure (X11/Web Color)", 0xF0FFFF),
	BABY_BLUE 					("Baby Blue", 0x89CFF0),
	BABY_BLUE_EYES 				("Baby Blue Eyes", 0xA1CAF1),
	BABY_PINK 					("Baby Pink", 0xF4C2C2),
	BABY_POWDER 				("Baby Powder", 0xFEFEFA),
	BAKER_MILLER_PINK 			("Baker-Miller Pink", 0xFF91AF),
	BANANA_MANIA 				("Banana Mania", 0xFAE7B5),
	BARN_RED 					("Barn Red", 0x7C0A02),
	BATTLESHIP_GREY 			("Battleship Grey", 0x848482),
	BEAU_BLUE 					("Beau Blue", 0xBCD4E6),
	BEAVER 						("Beaver", 0x9F8170),
	BEIGE 						("Beige", 0xF5F5DC),
	B_DAZZLED_BLUE 				("B'dazzled Blue", 0x2E5894),
	BIG_DIP_O_RUBY 				("Big Dip O’ruby", 0x9C2542),
	BISQUE 						("Bisque", 0xFFE4C4),
	BISTRE 						("Bistre", 0x3D2B1F),
	BISTRE_BROWN 				("Bistre Brown", 0x967117),
	BITTER_LEMON 				("Bitter Lemon", 0xCAE00D),
	BLACK 						("Black", 0x000000),
	BLACK_BEAN 					("Black Bean", 0x3D0C02),
	BLACK_CORAL 				("Black Coral", 0x54626F),
	BLACK_OLIVE 				("Black Olive", 0x3B3C36),
	BLACK_SHADOWS 				("Black Shadows", 0xBFAFB2),
	BLANCHED_ALMOND 			("Blanched Almond", 0xFFEBCD),
	BLAST_OFF_BRONZE 			("Blast-Off Bronze", 0xA57164),
	BLEU_DE_FRANCE 				("Bleu De France", 0x318CE7),
	BLIZZARD_BLUE 				("Blizzard Blue", 0xACE5EE),
	BLOOD_RED 					("Blood Red", 0x660000),
	BLUE 						("Blue", 0x0000FF),
	BLUE_CRAYOLA 				("Blue (Crayola)", 0x1F75FE),
	BLUE_MUNSELL 				("Blue (Munsell)", 0x0093AF),
	BLUE_NCS 					("Blue (Ncs)", 0x0087BD),
	BLUE_PANTONE 				("Blue (Pantone)", 0x0018A8),
	BLUE_PIGMENT 				("Blue (Pigment)", 0x333399),
	BLUE_BELL 					("Blue Bell", 0xA2A2D0),
	BLUE_GRAY_CRAYOLA 			("Blue-Gray (Crayola)", 0x6699CC),
	BLUE_JEANS 					("Blue Jeans", 0x5DADEC),
	BLUE_SAPPHIRE 				("Blue Sapphire", 0x126180),
	BLUE_VIOLET 				("Blue-Violet", 0x8A2BE2),
	BLUE_YONDER 				("Blue Yonder", 0x5072A7),
	BLUETIFUL 					("Bluetiful", 0x3C69E7),
	BLUSH 						("Blush", 0xDE5D83),
	BOLE 						("Bole", 0x79443B),
	BONE 						("Bone", 0xE3DAC9),
	BRICK_RED 					("Brick Red", 0xCB4154),
	BRIGHT_LILAC 				("Bright Lilac", 0xD891EF),
	BRIGHT_YELLOW_CRAYOLA 		("Bright Yellow  (Crayola)", 0xFFAA1D),
	BRONZE 						("Bronze", 0xCD7F32),
	BROWN_SUGAR 				("Brown Sugar", 0xAF6E4D),
	BUD_GREEN 					("Bud Green", 0x7BB661),
	BUFF 						("Buff", 0xFFC680),
	BURGUNDY 					("Burgundy", 0x800020),
	BURLYWOOD 					("Burlywood", 0xDEB887),
	BURNISHED_BROWN 			("Burnished Brown", 0xA17A74),
	BURNT_ORANGE 				("Burnt Orange", 0xCC5500),
	BURNT_SIENNA 				("Burnt Sienna", 0xE97451),
	BURNT_UMBER 				("Burnt Umber", 0x8A3324),
	BYZANTINE 					("Byzantine", 0xBD33A4),
	BYZANTIUM 					("Byzantium", 0x702963),
	CADET_BLUE 					("Cadet Blue", 0x5F9EA0),
	CADET_GREY 					("Cadet Grey", 0x91A3B0),
	CADMIUM_GREEN 				("Cadmium Green", 0x006B3C),
	CADMIUM_ORANGE 				("Cadmium Orange", 0xED872D),
	CAFÉ_AU_LAIT 				("Café Au Lait", 0xA67B5B),
	CAFÉ_NOIR 					("Café Noir", 0x4B3621),
	CAMBRIDGE_BLUE 				("Cambridge Blue", 0xA3C1AD),
	CAMEL 						("Camel", 0xC19A6B),
	CAMEO_PINK 					("Cameo Pink", 0xEFBBCC),
	CANARY 						("Canary", 0xFFFF99),
	CANARY_YELLOW 				("Canary Yellow", 0xFFEF00),
	CANDY_PINK 					("Candy Pink", 0xE4717A),
	CARDINAL 					("Cardinal", 0xC41E3A),
	CARIBBEAN_GREEN 			("Caribbean Green", 0x00CC99),
	CARMINE 					("Carmine", 0x960018),
	CARMINE_MP 					("Carmine (M&P)", 0xD70040),
	CARNATION_PINK 				("Carnation Pink", 0xFFA6C9),
	CARNELIAN 					("Carnelian", 0xB31B1B),
	CAROLINA_BLUE 				("Carolina Blue", 0x56A0D3),
	CARROT_ORANGE 				("Carrot Orange", 0xED9121),
	CATAWBA 					("Catawba", 0x703642),
	CEDAR_CHEST 				("Cedar Chest", 0xC95A49),
	CELADON 					("Celadon", 0xACE1AF),
	CELESTE 					("Celeste", 0xB2FFFF),
	CERISE 						("Cerise", 0xDE3163),
	CERULEAN 					("Cerulean", 0x007BA7),
	CERULEAN_BLUE 				("Cerulean Blue", 0x2A52BE),
	CERULEAN_FROST 				("Cerulean Frost", 0x6D9BC3),
	CERULEAN_CRAYOLA 			("Cerulean (Crayola)", 0x1DACD6),
	CHAMPAGNE 					("Champagne", 0xF7E7CE),
	CHAMPAGNE_PINK 				("Champagne Pink", 0xF1DDCF),
	CHARCOAL 					("Charcoal", 0x36454F),
	CHARM_PINK 					("Charm Pink", 0xE68FAC),
	CHARTREUSE_WEB 				("Chartreuse (Web)", 0x80FF00),
	CHERRY_BLOSSOM_PINK 		("Cherry Blossom Pink", 0xFFB7C5),
	CHESTNUT 					("Chestnut", 0x954535),
	CHILI_RED 					("Chili Red", 0xE23D28),
	CHINA_PINK 					("China Pink", 0xDE6FA1),
	CHINESE_RED 				("Chinese Red", 0xAA381E),
	CHINESE_VIOLET 				("Chinese Violet", 0x856088),
	CHINESE_YELLOW 				("Chinese Yellow", 0xFFB200),
	CHOCOLATE_TRADITIONAL 		("Chocolate (Traditional)", 0x7B3F00),
	CHOCOLATE_WEB 				("Chocolate (Web)", 0xD2691E),
	CINEREOUS 					("Cinereous", 0x98817B),
	CINNABAR 					("Cinnabar", 0xE34234),
	CINNAMON_SATIN 				("Cinnamon Satin", 0xCD607E),
	CITRINE 					("Citrine", 0xE4D00A),
	CITRON 						("Citron", 0x9FA91F),
	CLARET 						("Claret", 0x7F1734),
	COFFEE 						("Coffee", 0x6F4E37),
	COLUMBIA_BLUE 				("Columbia Blue", 0xB9D9EB),
	CONGO_PINK 					("Congo Pink", 0xF88379),
	COOL_GREY 					("Cool Grey", 0x8C92AC),
	COPPER 						("Copper", 0xB87333),
	COPPER_CRAYOLA 				("Copper (Crayola)", 0xDA8A67),
	COPPER_PENNY 				("Copper Penny", 0xAD6F69),
	COPPER_RED 					("Copper Red", 0xCB6D51),
	COPPER_ROSE 				("Copper Rose", 0x996666),
	COQUELICOT 					("Coquelicot", 0xFF3800),
	CORAL 						("Coral", 0xFF7F50),
	CORAL_PINK 					("Coral Pink", 0xF88379),
	CORDOVAN 					("Cordovan", 0x893F45),
	CORN 						("Corn", 0xFBEC5D),
	CORNFLOWER_BLUE 			("Cornflower Blue", 0x6495ED),
	CORNSILK 					("Cornsilk", 0xFFF8DC),
	COSMIC_COBALT 				("Cosmic Cobalt", 0x2E2D88),
	COSMIC_LATTE 				("Cosmic Latte", 0xFFF8E7),
	COYOTE_BROWN 				("Coyote Brown", 0x81613C),
	COTTON_CANDY 				("Cotton Candy", 0xFFBCD9),
	CREAM 						("Cream", 0xFFFDD0),
	CRIMSON 					("Crimson", 0xDC143C),
	CRIMSON_UA 					("Crimson (Ua)", 0x9E1B32),
	CULTURED_PEARL 				("Cultured Pearl", 0xF5F5F5),
	CYAN 						("Cyan", 0x00FFFF),
	CYAN_PROCESS 				("Cyan (Process)", 0x00B7EB),
	CYBER_GRAPE 				("Cyber Grape", 0x58427C),
	CYBER_YELLOW 				("Cyber Yellow", 0xFFD300),
	CYCLAMEN 					("Cyclamen", 0xF56FA1),
	DARK_BROWN 					("Dark Brown", 0x654321),
	DARK_BYZANTIUM 				("Dark Byzantium", 0x5D3954),
	DARK_CYAN 					("Dark Cyan", 0x008B8B),
	DARK_ELECTRIC_BLUE 			("Dark Electric Blue", 0x536878),
	DARK_GOLDENROD 				("Dark Goldenrod", 0xB8860B),
	DARK_GREEN_X11 				("Dark Green (X11)", 0x006400),
	DARK_JUNGLE_GREEN 			("Dark Jungle Green", 0x1A2421),
	DARK_KHAKI 					("Dark Khaki", 0xBDB76B),
	DARK_LAVA 					("Dark Lava", 0x483C32),
	DARK_LIVER_HORSES 			("Dark Liver (Horses)", 0x543D37),
	DARK_MAGENTA 				("Dark Magenta", 0x8B008B),
	DARK_OLIVE_GREEN 			("Dark Olive Green", 0x556B2F),
	DARK_ORANGE 				("Dark Orange", 0xFF8C00),
	DARK_ORCHID 				("Dark Orchid", 0x9932CC),
	DARK_PURPLE 				("Dark Purple", 0x301934),
	DARK_RED 					("Dark Red", 0x8B0000),
	DARK_SALMON 				("Dark Salmon", 0xE9967A),
	DARK_SEA_GREEN 				("Dark Sea Green", 0x8FBC8F),
	DARK_SIENNA 				("Dark Sienna", 0x3C1414),
	DARK_SKY_BLUE 				("Dark Sky Blue", 0x8CBED6),
	DARK_SLATE_BLUE 			("Dark Slate Blue", 0x483D8B),
	DARK_SLATE_GRAY 			("Dark Slate Gray", 0x2F4F4F),
	DARK_SPRING_GREEN 			("Dark Spring Green", 0x177245),
	DARK_TURQUOISE 				("Dark Turquoise", 0x00CED1),
	DARK_VIOLET 				("Dark Violet", 0x9400D3),
	DAVYS_GREY 					("Davy's Grey", 0x555555),
	DEEP_CERISE 				("Deep Cerise", 0xDA3287),
	DEEP_CHAMPAGNE 				("Deep Champagne", 0xFAD6A5),
	DEEP_CHESTNUT 				("Deep Chestnut", 0xB94E48),
	DEEP_JUNGLE_GREEN 			("Deep Jungle Green", 0x004B49),
	DEEP_PINK 					("Deep Pink", 0xFF1493),
	DEEP_SAFFRON 				("Deep Saffron", 0xFF9933),
	DEEP_SKY_BLUE 				("Deep Sky Blue", 0x00BFFF),
	DEEP_SPACE_SPARKLE 			("Deep Space Sparkle", 0x4A646C),
	DEEP_TAUPE 					("Deep Taupe", 0x7E5E60),
	DENIM 						("Denim", 0x1560BD),
	DENIM_BLUE 					("Denim Blue", 0x2243B6),
	DESERT 						("Desert", 0xC19A6B),
	DESERT_SAND 				("Desert Sand", 0xEDC9AF),
	DIM_GRAY 					("Dim Gray", 0x696969),
	DODGER_BLUE 				("Dodger Blue", 0x1E90FF),
	DRAB_DARK_BROWN 			("Drab Dark Brown", 0x4A412A),
	DUKE_BLUE 					("Duke Blue", 0x00009C),
	DUTCH_WHITE 				("Dutch White", 0xEFDFBB),
	EBONY 						("Ebony", 0x555D50),
	ECRU 						("Ecru", 0xC2B280),
	EERIE_BLACK 				("Eerie Black", 0x1B1B1B),
	EGGPLANT 					("Eggplant", 0x614051),
	EGGSHELL 					("Eggshell", 0xF0EAD6),
	ELECTRIC_LIME 				("Electric Lime", 0xCCFF00),
	ELECTRIC_PURPLE 			("Electric Purple", 0xBF00FF),
	ELECTRIC_VIOLET 			("Electric Violet", 0x8F00FF),
	EMERALD 					("Emerald", 0x50C878),
	EMINENCE 					("Eminence", 0x6C3082),
	ENGLISH_LAVENDER 			("English Lavender", 0xB48395),
	ENGLISH_RED 				("English Red", 0xAB4B52),
	ENGLISH_VERMILLION 			("English Vermillion", 0xCC474B),
	ENGLISH_VIOLET 				("English Violet", 0x563C5C),
	ERIN 						("Erin", 0x00FF40),
	ETON_BLUE 					("Eton Blue", 0x96C8A2),
	FALLOW 						("Fallow", 0xC19A6B),
	FALU_RED 					("Falu Red", 0x801818),
	FANDANGO 					("Fandango", 0xB53389),
	FANDANGO_PINK 				("Fandango Pink", 0xDE5285),
	FAWN 						("Fawn", 0xE5AA70),
	FERN_GREEN 					("Fern Green", 0x4F7942),
	FIELD_DRAB 					("Field Drab", 0x6C541E),
	FIERY_ROSE 					("Fiery Rose", 0xFF5470),
	FINN 						("Finn", 0x683068),
	FIREBRICK 					("Firebrick", 0xB22222),
	FIRE_ENGINE_RED 			("Fire Engine Red", 0xCE2029),
	FLAME 						("Flame", 0xE25822),
	FLAX 						("Flax", 0xEEDC82),
	FLIRT 						("Flirt", 0xA2006D),
	FLORAL_WHITE 				("Floral White", 0xFFFAF0),
	FOREST_GREEN_WEB 			("Forest Green (Web)", 0x228B22),
	FRENCH_BEIGE 				("French Beige", 0xA67B5B),
	FRENCH_BISTRE 				("French Bistre", 0x856D4D),
	FRENCH_BLUE 				("French Blue", 0x0072BB),
	FRENCH_FUCHSIA 				("French Fuchsia", 0xFD3F92),
	FRENCH_LILAC 				("French Lilac", 0x86608E),
	FRENCH_LIME 				("French Lime", 0x9EFD38),
	FRENCH_MAUVE 				("French Mauve", 0xD473D4),
	FRENCH_PINK 				("French Pink", 0xFD6C9E),
	FRENCH_RASPBERRY 			("French Raspberry", 0xC72C48),
	FRENCH_SKY_BLUE 			("French Sky Blue", 0x77B5FE),
	FRENCH_VIOLET 				("French Violet", 0x8806CE),
	FROSTBITE 					("Frostbite", 0xE936A7),
	FUCHSIA 					("Fuchsia", 0xFF00FF),
	FUCHSIA_CRAYOLA 			("Fuchsia (Crayola)", 0xC154C1),
	FULVOUS 					("Fulvous", 0xE48400),
	FUZZY_WUZZY 				("Fuzzy Wuzzy", 0x87421F),
	
	
	
	
	NADESHIKO_PINK	 	 	 	("Nadeshiko pink", 0xF6ADC6),
	NAPLES_YELLOW	 	 	 	("Naples yellow", 0xFADA5E),
	NAVAJO_WHITE	 	 	 	("Navajo white", 0xFFDEAD),
	NAVY_BLUE	 	 	 		("Navy blue", 0x80),
	NAVY_BLUE_CRAYOLA	 	 	("Navy blue (Crayola)", 0x1974D2),
	NEON_BLUE	 	 	 		("Neon blue", 0x4666FF),
	NEON_GREEN	 	 	 		("Neon green", 0x39FF14),
	NEON_FUCHSIA	 	 	 	("Neon fuchsia", 0xFE4164),
	NEW_YORK_PINK	 	 	 	("New York pink", 0xD7837F),
	NICKEL	 	 	 			("Nickel", 0x727472),
	NON_PHOTO_BLUE	 	 	 	("Non-photo blue", 0xA4DDED),
	NYANZA	 	 	 			("Nyanza", 0xE9FFDB),
	OCHRE	 	 	 			("Ochre", 0xCC7722),
	OLD_BURGUNDY	 	 	 	("Old burgundy", 0x43302E),
	OLD_GOLD	 	 	 		("Old gold", 0xCFB53B),
	OLD_LACE	 	 	 		("Old lace", 0xFDF5E6),
	OLD_LAVENDER	 	 	 	("Old lavender", 0x796878),
	OLD_MAUVE	 	 	 		("Old mauve", 0x673147),
	OLD_ROSE	 	 	 		("Old rose", 0xC08081),
	OLD_SILVER	 	 	 		("Old silver", 0x848482),
	OLIVE	 	 	 			("Olive", 0x808000),
	OLIVE_DRAB_0X3	 	 	 	("Olive Drab (0x3)", 0x6B8E23),
	OLIVE_DRAB_0X7	 	 	 	("Olive Drab 0x7", 0x3C341F),
	OLIVE_GREEN	 	 	 		("Olive green", 0xB5B35C),
	OLIVINE	 	 	 			("Olivine", 0x9AB973),
	ONYX	 	 	 			("Onyx", 0x353839),
	OPAL	 	 	 			("Opal", 0xA8C3BC),
	OPERA_MAUVE	 	 	 		("Opera mauve", 0xB784A7),
	ORANGE	 	 	 			("Orange", 0xFF7F00),
	ORANGE_CRAYOLA	 	 	 	("Orange (Crayola)", 0xFF7538),
	ORANGE_PANTONE	 	 	 	("Orange (Pantone)", 0xFF5800),
	ORANGE_WEB	 	 	 		("Orange (web)", 0xFFA500),
	ORANGE_PEEL	 	 	 		("Orange peel", 0xFF9F00),
	ORANGE_RED	 	 	 		("Orange-red", 0xFF681F),
	ORANGE_RED_CRAYOLA	 	 	("Orange-red (Crayola)", 0xFF5349),
	ORANGE_SODA	 	 	 		("Orange Soda", 0xFA5B3D),
	ORANGE_YELLOW	 	 	 	("Orange-yellow", 0xF5BD1F),
	ORANGE_YELLOW_CRAYOLA	 	("Orange-yellow (Crayola)", 0xF8D568),
	ORCHID	 	 	 			("Orchid", 0xDA70D6),
	ORCHID_PINK	 	 	 		("Orchid pink", 0xF2BDCD),
	ORCHID_CRAYOLA	 	 	 	("Orchid (Crayola)", 0xE29CD2),
	OUTER_SPACE_CRAYOLA	 	 	("Outer space (Crayola)", 0x2D383A),
	OUTRAGEOUS_ORANGE	 	 	("Outrageous Orange", 0xFF6E4A),
	OXBLOOD	 	 	 			("Oxblood", 0x4A0000),
	OXFORD_BLUE	 	 	 		("Oxford blue", 0x2147),
	OU_CRIMSON_RED	 	 	 	("OU Crimson red", 0x841617),
	PACIFIC_BLUE	 	 	 	("Pacific blue", 0x1CA9C9),
	PAKISTAN_GREEN	 	 	 	("Pakistan green", 0x6600),
	PALATINATE_PURPLE	 	 	("Palatinate purple", 0x682860),
	PALE_AQUA	 	 	 		("Pale aqua", 0xBED3E5),
	PALE_CERULEAN	 	 	 	("Pale cerulean", 0x9BC4E2),
	PALE_DOGWOOD	 	 	 	("Pale Dogwood", 0xED7A9B),
	PALE_PINK	 	 	 		("Pale pink", 0xFADADD),
	PALE_PURPLE_PANTONE	 	 	("Pale purple (Pantone)", 0xFAE6FA),
	PALE_SPRING_BUD	 	 	 	("Pale spring bud", 0xECEBBD),
	PANSY_PURPLE	 	 	 	("Pansy purple", 0x78184A),
	PAOLO_VERONESE_GREEN	 	("Paolo Veronese green", 0x9B7D),
	PAPAYA_WHIP	 	 	 		("Papaya whip", 0xFFEFD5),
	PARADISE_PINK	 	 	 	("Paradise pink", 0xE63E62),
	PARCHMENT	 	 	 		("Parchment", 0xF1E9D2),
	PARIS_GREEN	 	 	 		("Paris Green", 0x50C878),
	PASTEL_PINK	 	 	 		("Pastel pink", 0xDEA5A4),
	PATRIARCH	 	 	 		("Patriarch", 0x800080),
	PAUA	 	 	 			("Paua", 0x1F005E),
	PAYNES_GREY	 	 	 		("Payne's grey", 0x536878),
	PEACH	 	 	 			("Peach", 0xFFE5B4),
	PEACH_CRAYOLA	 	 	 	("Peach (Crayola)", 0xFFCBA4),
	PEACH_PUFF	 	 	 		("Peach puff", 0xFFDAB9),
	PEAR	 	 	 			("Pear", 0xD1E231),
	PEARLY_PURPLE	 	 	 	("Pearly purple", 0xB768A2),
	PERIWINKLE	 	 	 		("Periwinkle", 0xCCCCFF),
	PERIWINKLE_CRAYOLA	 	 	("Periwinkle (Crayola)", 0xC3CDE6),
	PERMANENT_GERANIUM_LAKE	 	("Permanent Geranium Lake", 0xE12C2C),
	PERSIAN_BLUE	 	 	 	("Persian blue", 0x1C39BB),
	PERSIAN_GREEN	 	 	 	("Persian green", 0xA693),
	PERSIAN_INDIGO	 	 	 	("Persian indigo", 0x32127A),
	PERSIAN_ORANGE	 	 	 	("Persian orange", 0xD99058),
	PERSIAN_PINK	 	 	 	("Persian pink", 0xF77FBE),
	PERSIAN_PLUM	 	 	 	("Persian plum", 0x701C1C),
	PERSIAN_RED	 	 	 		("Persian red", 0xCC3333),
	PERSIAN_ROSE	 	 	 	("Persian rose", 0xFE28A2),
	PERSIMMON	 	 	 		("Persimmon", 0xEC5800),
	PEWTER_BLUE	 	 	 		("Pewter Blue", 0x8BA8B7),
	PHLOX	 	 	 			("Phlox", 0xDF00FF),
	PHTHALO_BLUE	 	 	 	("Phthalo blue", 0xF89),
	PHTHALO_GREEN	 	 	 	("Phthalo green", 0x123524),
	PICOTEE_BLUE	 	 	 	("Picotee blue", 0x2E2787),
	PICTORIAL_CARMINE	 	 	("Pictorial carmine", 0xC30B4E),
	PIGGY_PINK	 	 	 		("Piggy pink", 0xFDDDE6),
	PINE_GREEN	 	 	 		("Pine green", 0x1796F),
	PINE_TREE	 	 	 		("Pine tree", 0x2A2F23),
	PINK	 	 	 			("Pink", 0xFFC0CB),
	PINK_PANTONE	 	 	 	("Pink (Pantone)", 0xD74894),
	PINK_LACE	 	 			("Pink lace", 0xFFDDF4),
	PINK_LAVENDER	 	 	 	("Pink lavender", 0xD8B2D1),
	PINK_SHERBET	 	 	 	("Pink Sherbet", 0xF78FA7),
	PISTACHIO	 	 	 		("Pistachio", 0x93C572),
	PLATINUM	 	 	 		("Platinum", 0xE5E4E2),
	PLUM	 	 	 			("Plum", 0x8E4585),
	PLUM_WEB	 	 	 		("Plum (web)", 0xDDA0DD),
	PLUMP_PURPLE	 	 	 	("Plump Purple", 0x5946B2),
	POLISHED_PINE	 	 	 	("Polished Pine", 0x5DA493),
	POMP_AND_POWER	 	 	 	("Pomp and Power", 0x86608E),
	POPSTAR	 	 	 			("Popstar", 0xBE4F62),
	PORTLAND_ORANGE	 	 	 	("Portland Orange", 0xFF5A36),
	POWDER_BLUE	 	 	 		("Powder blue", 0xB0E0E6),
	PRINCETON_ORANGE	 	 	("Princeton orange", 0xF58025),
	PROCESS_YELLOW	 	 	 	("Process yellow", 0xFFEF00),
	PRUNE	 	 	 			("Prune", 0x701C1C),
	PRUSSIAN_BLUE	 	 	 	("Prussian blue", 0x3153),
	PSYCHEDELIC_PURPLE	 	 	("Psychedelic purple", 0xDF00FF),
	PUCE	 	 	 			("Puce", 0xCC8899),
	PULLMAN_BROWN_UPS_BROWN	 	("Pullman Brown (UPS Brown)", 0x644117),
	PUMPKIN	 	 	 			("Pumpkin", 0xFF7518),
	PURPLE	 	 	 			("Purple", 0x6A0DAD),
	PURPLE_WEB	 	 	 		("Purple (web)", 0x800080),
	PURPLE_MUNSELL	 	 	 	("Purple (Munsell)", 0x9F00C5),
	PURPLE_X11	 	 	 		("Purple (X11)", 0xA020F0),
	PURPLE_MOUNTAIN_MAJESTY	 	("Purple mountain majesty", 0x9678B6),
	PURPLE_NAVY	 	 	 		("Purple navy", 0x4E5180),
	PURPLE_PIZZAZZ	 	 	 	("Purple pizzazz", 0xFE4EDA),
	PURPLE_PLUM	 	 	 		("Purple Plum", 0x9C51B6),
	PURPUREUS	 	 	 		("Purpureus", 0x9A4EAE),
	QUEEN_BLUE	 	 	 		("Queen blue", 0x436B95),
	QUEEN_PINK	 	 	 		("Queen pink", 0xE8CCD7),
	QUICK_SILVER	 	 	 	("Quick Silver", 0xA6A6A6),
	QUINACRIDONE_MAGENTA	 	("Quinacridone magenta", 0x8E3A59),
	RADICAL_RED	 	 	 		("Radical Red", 0xFF355E),
	RAISIN_BLACK	 	 	 	("Raisin black", 0x242124),
	RAJAH	 	 	 			("Rajah", 0xFBAB60),
	RASPBERRY	 	 	 		("Raspberry", 0xE30B5D),
	RASPBERRY_GLACÉ	 	 	 	("Raspberry glacé", 0x915F6D),
	RASPBERRY_ROSE	 	 	 	("Raspberry rose", 0xB3446C),
	RAW_SIENNA	 	 	 		("Raw sienna", 0xD68A59),
	RAW_UMBER	 	 	 		("Raw umber", 0x826644),
	RAZZLE_DAZZLE_ROSE	 	 	("Razzle dazzle rose", 0xFF33CC),
	RAZZMATAZZ	 	 	 		("Razzmatazz", 0xE3256B),
	RAZZMIC_BERRY	 	 	 	("Razzmic Berry", 0x8D4E85),
	REBECCA_PURPLE	 	 	 	("Rebecca Purple", 0x663399),
	RED	 	 	 				("Red", 0xFF0000),
	RED_CRAYOLA	 	 	 		("Red (Crayola)", 0xEE204D),
	RED_MUNSELL	 	 	 		("Red (Munsell)", 0xF2003C),
	RED_NCS	 	 	 			("Red (NCS)", 0xC40233),
	RED_PANTONE	 	 	 		("Red (Pantone)", 0xED2939),
	RED_PIGMENT	 	 	 		("Red (pigment)", 0xED1C24),
	RED_RYB	 	 	 			("Red (RYB)", 0xFE2712),
	RED_ORANGE	 	 	 		("Red-orange", 0xFF5349),
	RED_ORANGE_CRAYOLA	 	 	("Red-orange (Crayola)", 0xFF681F),
	RED_ORANGE_COLOR_WHEEL	 	("Red-orange (Color wheel)", 0xFF4500),
	RED_PURPLE	 	 	 		("Red-purple", 0xE40078),
	RED_SALSA	 	 	 		("Red Salsa", 0xFD3A4A),
	RED_VIOLET	 	 	 		("Red-violet", 0xC71585),
	RED_VIOLET_CRAYOLA	 	 	("Red-violet (Crayola)", 0xC0448F),
	RED_VIOLET_COLOR_WHEEL	 	("Red-violet (Color wheel)", 0x922B3E),
	REDWOOD	 	 	 			("Redwood", 0xA45A52),
	RESOLUTION_BLUE	 	 	 	("Resolution blue", 0x2387),
	RHYTHM	 	 	 			("Rhythm", 0x777696),
	RICH_BLACK	 	 	 		("Rich black", 0x4040),
	RICH_BLACK_FOGRA29	 	 	("Rich black (FOGRA29)", 0x10B13),
	RICH_BLACK_FOGRA39	 		("Rich black (FOGRA39)", 0x10203),
	RIFLE_GREEN	 	 	 		("Rifle green", 0x444C38),
	ROBIN_EGG_BLUE	 	 	 	("Robin egg blue", 0xCCCC),
	ROCKET_METALLIC	 	 	 	("Rocket metallic", 0x8A7F80),
	ROJO_SPANISH_RED	 		("Rojo Spanish red", 0xA91101),
	ROMAN_SILVER	 	 	 	("Roman silver", 0x838996),
	ROSE	 	 	 			("Rose", 0xFF007F),
	ROSE_BONBON	 	 	 		("Rose bonbon", 0xF9429E),
	ROSE_DUST	 	 	 		("Rose Dust", 0x9E5E6F),
	ROSE_EBONY	 	 	 		("Rose ebony", 0x674846),
	ROSE_MADDER	 	 	 		("Rose madder", 0xE32636),
	ROSE_PINK	 	 	 		("Rose pink", 0xFF66CC),
	ROSE_POMPADOUR	 	 	 	("Rose Pompadour", 0xED7A9B),
	ROSE_RED	 	 	 		("Rose red", 0xC21E56),
	ROSE_TAUPE	 	 	 		("Rose taupe", 0x905D5D),
	ROSE_VALE	 	 	 		("Rose vale", 0xAB4E52),
	ROSEWOOD	 	 	 		("Rosewood", 0x65000B),
	ROSSO_CORSA	 	 	 		("Rosso corsa", 0xD40000),
	ROSY_BROWN	 	 	 		("Rosy brown", 0xBC8F8F),
	ROYAL_BLUE_DARK	 	 	 	("Royal blue (dark)", 0x2366),
	ROYAL_BLUE_LIGHT	 	 	("Royal blue (light)", 0x4169E1),
	ROYAL_PURPLE	 	 	 	("Royal purple", 0x7851A9),
	ROYAL_YELLOW	 	 	 	("Royal yellow", 0xFADA5E),
	RUBER	 	 	 			("Ruber", 0xCE4676),
	RUBINE_RED	 	 	 		("Rubine red", 0xD10056),
	RUBY	 	 	 			("Ruby", 0xE0115F),
	RUBY_RED	 	 	 		("Ruby red", 0x9B111E),
	RUFOUS	 	 	 			("Rufous", 0xA81C07),
	RUSSET	 	 	 			("Russet", 0x80461B),
	RUSSIAN_GREEN	 	 	 	("Russian green", 0x679267),
	RUSSIAN_VIOLET	 	 	 	("Russian violet", 0x32174D),
	RUST	 	 	 			("Rust", 0xB7410E),
	RUSTY_RED	 	 	 		("Rusty red", 0xDA2C43),
	SACRAMENTO_STATE_GREEN	 	("Sacramento State green", 0x43927),
	SADDLE_BROWN	 	 	 	("Saddle brown", 0x8B4513),
	SAFETY_ORANGE	 	 	 	("Safety orange", 0xFF7800),
	SAFETY_ORANGE_BLAZE_ORANGE	("Safety orange (blaze orange)", 0xFF6700),
	SAFETY_YELLOW	 	 	 	("Safety yellow", 0xEED202),
	SAFFRON	 	 	 			("Saffron", 0xF4C430),
	SAGE	 	 	 			("Sage", 0xBCB88A),
	ST_PATRICKS_BLUE	 	 	("St. Patrick's blue", 0x23297A),
	SALMON	 	 	 			("Salmon", 0xFA8072),
	SALMON_PINK	 	 	 		("Salmon pink", 0xFF91A4),
	SAND	 	 	 			("Sand", 0xC2B280),
	SAND_DUNE	 	 	 		("Sand dune", 0x967117),
	SANDY_BROWN	 	 	 		("Sandy brown", 0xF4A460),
	SAP_GREEN	 	 	 		("Sap green", 0x507D2A),
	SAPPHIRE	 	 	 		("Sapphire", 0xF52BA),
	SAPPHIRE_BLUE	 	 	 	("Sapphire blue", 0x67A5),
	SAPPHIRE_CRAYOLA	 	 	("Sapphire (Crayola)", 0x2D5DA1),
	SATIN_SHEEN_GOLD	 	 	("Satin sheen gold", 0xCBA135),
	SCARLET	 	 	 			("Scarlet", 0xFF2400),
	SCHAUSS_PINK	 	 	 	("Schauss pink", 0xFF91AF),
	SCHOOL_BUS_YELLOW	 	 	("School bus yellow", 0xFFD800),
	SCREAMIN_GREEN	 	 	 	("Screamin' Green", 0x66FF66),
	SEA_GREEN	 	 	 		("Sea green", 0x2E8B57),
	SEA_GREEN_CRAYOLA	 	 	("Sea green (Crayola)", 0xFFCD),
	SEANCE	 	 	 			("Seance", 0x612086),
	SEAL_BROWN	 	 	 		("Seal brown", 0x59260B),
	SEASHELL	 	 	 		("Seashell", 0xFFF5EE),
	SECRET	 	 	 			("Secret", 0x764374),
	SELECTIVE_YELLOW	 	 	("Selective yellow", 0xFFBA00),
	SEPIA	 	 	 			("Sepia", 0x704214),
	SHADOW	 	 	 			("Shadow", 0x8A795D),
	SHADOW_BLUE	 	 	 		("Shadow blue", 0x778BA5),
	SHAMROCK_GREEN	 	 	 	("Shamrock green", 0x9E60),
	SHEEN_GREEN	 	 	 		("Sheen green", 0x8FD400),
	SHIMMERING_BLUSH	 	 	("Shimmering Blush", 0xD98695),
	SHINY_SHAMROCK	 	 	 	("Shiny Shamrock", 0x5FA778),
	SHOCKING_PINK	 	 	 	("Shocking pink", 0xFC0FC0),
	SHOCKING_PINK_CRAYOLA	 	("Shocking pink (Crayola)", 0xFF6FFF),
	SIENNA	 	 	 			("Sienna", 0x882D17),
	SILVER	 	 	 			("Silver", 0xC0C0C0),
	SILVER_CRAYOLA	 	 	 	("Silver (Crayola)", 0xC9C0BB),
	SILVER_METALLIC	 	 	 	("Silver (Metallic)", 0xAAA9AD),
	SILVER_CHALICE	 	 	 	("Silver chalice", 0xACACAC),
	SILVER_PINK	 	 	 		("Silver pink", 0xC4AEAD),
	SILVER_SAND	 	 	 		("Silver sand", 0xBFC1C2),
	SINOPIA	 	 	 			("Sinopia", 0xCB410B),
	SIZZLING_RED	 	 	 	("Sizzling Red", 0xFF3855),
	SIZZLING_SUNRISE	 	 	("Sizzling Sunrise", 0xFFDB00),
	SKOBELOFF	 	 	 		("Skobeloff", 0x7474),
	SKY_BLUE	 	 	 		("Sky blue", 0x87CEEB),
	SKY_BLUE_CRAYOLA	 	 	("Sky blue (Crayola)", 0x76D7EA),
	SKY_MAGENTA	 	 	 		("Sky magenta", 0xCF71AF),
	SLATE_BLUE	 	 	 		("Slate blue", 0x6A5ACD),
	SLATE_GRAY	 	 	 		("Slate gray", 0x708090),
	SLIMY_GREEN	 	 	 		("Slimy green", 0x299617),
	SMITTEN	 	 	 			("Smitten", 0xC84186),
	SMOKY_BLACK	 	 	 		("Smoky black", 0x100C08),
	SNOW	 	 	 			("Snow", 0xFFFAFA),
	SOLID_PINK	 	 	 		("Solid pink", 0x893843),
	SONIC_SILVER	 	 	 	("Sonic silver", 0x757575),
	SPACE_CADET	 	 	 		("Space cadet", 0x1D2951),
	SPANISH_BISTRE	 	 	 	("Spanish bistre", 0x807532),
	SPANISH_BLUE	 	 	 	("Spanish blue", 0x70B8),
	SPANISH_CARMINE	 	 	 	("Spanish carmine", 0xD10047),
	SPANISH_GRAY	 	 	 	("Spanish gray", 0x989898),
	SPANISH_GREEN	 	 	 	("Spanish green", 0x9150),
	SPANISH_ORANGE	 	 	 	("Spanish orange", 0xE86100),
	SPANISH_PINK	 	 	 	("Spanish pink", 0xF7BFBE),
	SPANISH_RED	 	 	 		("Spanish red", 0xE60026),
	SPANISH_SKY_BLUE	 	 	("Spanish sky blue", 0xFFFE),
	SPANISH_VIOLET	 	 	 	("Spanish violet", 0x4C2882),
	SPANISH_VIRIDIAN	 	 	("Spanish viridian", 0x7F5C),
	SPRING_BUD	 	 	 		("Spring bud", 0xA7FC00),
	SPRING_FROST	 	 	 	("Spring Frost", 0x87FF2A),
	SPRING_GREEN	 	 	 	("Spring green", 0xFF7F),
	SPRING_GREEN_CRAYOLA	 	("Spring green (Crayola)", 0xECEBBD),
	STAR_COMMAND_BLUE	 		("Star command blue", 0x7BB8),
	STEEL_BLUE	 	 	 		("Steel blue", 0x4682B4),
	STEEL_PINK	 	 	 		("Steel pink", 0xCC33CC),
	STIL_DE_GRAIN_YELLOW		("Stil de grain yellow", 0xFADA5E),
	STRAW	 	 	 			("Straw", 0xE4D96F),
	STRAWBERRY	 	 	 		("Strawberry", 0xFA5053),
	STRAWBERRY_BLONDE	 		("Strawberry Blonde", 0xFF9361),
	SUGAR_PLUM	 	 	 		("Sugar Plum", 0x914E75),
	SUNGLOW	 	 	 			("Sunglow", 0xFFCC33),
	SUNRAY	 	 	 			("Sunray", 0xE3AB57),
	SUNSET	 	 	 			("Sunset", 0xFAD6A5),
	SUPER_PINK	 	 	 		("Super pink", 0xCF6BA9),
	SWEET_BROWN	 	 	 		("Sweet Brown", 0xA83731),
	SYRACUSE_ORANGE	 	 	 	("Syracuse Orange", 0xD44500),
	TAN	 	 		 			("Tan", 0xD2B48C),
	TAN_CRAYOLA	 	 	 		("Tan (Crayola)", 0xD99A6C),
	TANGERINE	 	 	 		("Tangerine", 0xF28500),
	TANGO_PINK	 	 	 		("Tango pink", 0xE4717A),
	TART_ORANGE	 	 	 		("Tart Orange", 0xFB4D46),
	TAUPE	 	 	 			("Taupe", 0x483C32),
	TAUPE_GRAY	 	 	 		("Taupe gray", 0x8B8589),
	TEA_GREEN	 	 	 		("Tea green", 0xD0F0C0),
	TEA_ROSE	 	 	 		("Tea rose", 0xF4C2C2),
	TEAL	 	 	 			("Teal", 0x8080),
	TEAL_BLUE	 	 	 		("Teal blue", 0x367588),
	TELEMAGENTA	 	 	 		("Telemagenta", 0xCF3476),
	TENNÉ_TAWNY	 	 	 		("Tenné (tawny)", 0xCD5700),
	TERRA_COTTA	 	 	 		("Terra cotta", 0xE2725B),
	THISTLE	 	 	 			("Thistle", 0xD8BFD8),
	THULIAN_PINK	 	 	 	("Thulian pink", 0xDE6FA1),
	TICKLE_ME_PINK	 	 	 	("Tickle Me Pink", 0xFC89AC),
	TIFFANY_BLUE	 	 	 	("Tiffany Blue", 0xABAB5),
	TIMBERWOLF	 	 	 		("Timberwolf", 0xDBD7D2),
	TITANIUM_YELLOW	 	 	 	("Titanium yellow", 0xEEE600),
	TOMATO	 	 	 			("Tomato", 0xFF6347),
	TOURMALINE	 	 	 		("Tourmaline", 0x86A1A9),
	TROPICAL_RAINFOREST	 	 	("Tropical rainforest", 0x755E),
	TRUE_BLUE	 	 	 		("True Blue", 0x2D68C4),
	TRYPAN_BLUE	 	 	 		("Trypan Blue", 0x1C05B3),
	TUFTS_BLUE	 	 	 		("Tufts blue", 0x3E8EDE),
	TUMBLEWEED	 	 	 		("Tumbleweed", 0xDEAA88),
	TURQUOISE	 	 	 		("Turquoise", 0x40E0D0),
	TURQUOISE_BLUE	 	 	 	("Turquoise blue", 0xFFEF),
	TURQUOISE_GREEN	 	 	 	("Turquoise green", 0xA0D6B4),
	TURTLE_GREEN	 	 	 	("Turtle green", 0x8A9A5B),
	TUSCAN	 	 	 			("Tuscan", 0xFAD6A5),
	TUSCAN_BROWN	 	 	 	("Tuscan brown", 0x6F4E37),
	TUSCAN_RED	 	 	 		("Tuscan red", 0x7C4848),
	TUSCAN_TAN	 	 	 		("Tuscan tan", 0xA67B5B),
	TUSCANY	 	 	 			("Tuscany", 0xC09999),
	TWILIGHT_LAVENDER	 		("Twilight lavender", 0x8A496B),
	TYRIAN_PURPLE	 	 	 	("Tyrian purple", 0x66023C),
	UA_BLUE	 	 	 			("UA blue", 0x33AA),
	UA_RED	 	 	 			("UA red", 0xD9004C),
	ULTRAMARINE	 	 	 		("Ultramarine", 0x3F00FF),
	ULTRAMARINE_BLUE	 	 	("Ultramarine blue", 0x4166F5),
	ULTRA_PINK	 	 	 		("Ultra pink", 0xFF6FFF),
	ULTRA_RED	 	 	 		("Ultra red", 0xFC6C85),
	UMBER	 	 	 			("Umber", 0x635147),
	UNBLEACHED_SILK	 	 	 	("Unbleached silk", 0xFFDDCA),
	UNITED_NATIONS_BLUE	 		("United Nations blue", 0x5B92E5),
	UNIVERSITY_PENNSYLVANIA_RED	("University of Pennsylvania red", 0xA50021),
	UNMELLOW_YELLOW	 	 	 	("Unmellow yellow", 0xFFFF66),
	UP_FOREST_GREEN	 	 	 	("UP Forest green", 0x14421),
	UP_MAROON	 	 	 		("UP maroon", 0x7B1113),
	UPSDELL_RED	 	 	 		("Upsdell red", 0xAE2029),
	URANIAN_BLUE	 	 	 	("Uranian blue", 0xAFDBF5),
	USAFA_BLUE	 	 	 		("USAFA blue", 0x4F98),
	VAN_DYKE_BROWN	 	 	 	("Van Dyke brown", 0x664228),
	VANILLA	 	 	 			("Vanilla", 0xF3E5AB),
	VANILLA_ICE	 	 	 		("Vanilla ice", 0xF38FA9),
	VEGAS_GOLD	 	 	 		("Vegas gold", 0xC5B358),
	VENETIAN_RED	 	 	 	("Venetian red", 0xC80815),
	VERDIGRIS	 	 	 		("Verdigris", 0x43B3AE),
	VERMILION	 	 	 		("Vermilion", 0xE34234),
	VERONICA	 	 	 		("Veronica", 0xA020F0),
	VIOLET	 	 	 			("Violet", 0x8F00FF),
	VIOLET_COLOR_WHEEL	 	 	("Violet (color wheel)", 0x7F00FF),
	VIOLET_CRAYOLA	 	 	 	("Violet (crayola)", 0x963D7F),
	VIOLET_RYB	 	 	 		("Violet (RYB)", 0x8601AF),
	VIOLET_WEB	 	 	 		("Violet (web)", 0xEE82EE),
	VIOLET_BLUE	 	 	 		("Violet-blue", 0x324AB2),
	VIOLET_BLUE_CRAYOLA	 	 	("Violet-blue (Crayola)", 0x766EC8),
	VIOLET_RED	 	 	 		("Violet-red", 0xF75394),
	VIOLET_RED_PERBANG	 	 	("Violet-red(PerBang)", 0xF0599C),
	VIRIDIAN	 	 	 		("Viridian", 0x40826D),
	VIRIDIAN_GREEN	 	 	 	("Viridian green", 0x9698),
	VIVID_BURGUNDY	 	 	 	("Vivid burgundy", 0x9F1D35),
	VIVID_SKY_BLUE	 	 	 	("Vivid sky blue", 0xCCFF),
	VIVID_TANGERINE	 	 	 	("Vivid tangerine", 0xFFA089),
	VIVID_VIOLET	 	 	 	("Vivid violet", 0x9F00FF),
	VOLT	 	 	 			("Volt", 0xCEFF00),
	WARM_BLACK	 	 	 		("Warm black", 0x4242),
	WEEZY_BLUE	 	 	 		("Weezy Blue", 0x189BCC),
	WHEAT	 	 	 			("Wheat", 0xF5DEB3),
	WHITE	 	 	 			("White", 0xFFFFFF),
	WILD_BLUE_YONDER	 		("Wild blue yonder", 0xA2ADD0),
	WILD_ORCHID	 	 	 		("Wild orchid", 0xD470A2),
	WILD_STRAWBERRY	 	 	 	("Wild Strawberry", 0xFF43A4),
	WILD_WATERMELON	 	 	 	("Wild watermelon", 0xFC6C85),
	WINDSOR_TAN	 	 	 		("Windsor tan", 0xA75502),
	WINE	 	 	 			("Wine", 0x722F37),
	WINE_DREGS	 	 	 		("Wine dregs", 0x673147),
	WINTER_SKY	 	 	 		("Winter Sky", 0xFF007C),
	WINTERGREEN_DREAM	 		("Wintergreen Dream", 0x56887D),
	WISTERIA	 	 	 		("Wisteria", 0xC9A0DC),
	WOOD_BROWN	 	 	 		("Wood brown", 0xC19A6B),
	XANADU	 	 	 			("Xanadu", 0x738678),
	XANTHIC	 	 	 			("Xanthic", 0xEEED09),
	XANTHOUS	 	 	 		("Xanthous", 0xF1B42F),
	YALE_BLUE	 	 	 		("Yale Blue", 0x356B),
	YELLOW	 	 	 			("Yellow", 0xFFFF00),
	YELLOW_CRAYOLA	 	 	 	("Yellow (Crayola)", 0xFCE883),
	YELLOW_MUNSELL	 	 	 	("Yellow (Munsell)", 0xEFCC00),
	YELLOW_NCS	 	 	 		("Yellow (NCS)", 0xFFD300),
	YELLOW_PANTONE	 	 	 	("Yellow (Pantone)", 0xFEDF00),
	YELLOW_PROCESS	 	 	 	("Yellow (process)", 0xFFEF00),
	YELLOW_RYB	 	 	 		("Yellow (RYB)", 0xFEFE33),
	YELLOW_GREEN	 	 	 	("Yellow-green", 0x9ACD32),
	YELLOW_GREEN_CRAYOLA	 	("Yellow-green (Crayola)", 0xC5E384),
	YELLOW_GREEN_COLOR_WHEEL	("Yellow-green (Color Wheel)", 0x30B21A),
	YELLOW_ORANGE	 	 	 	("Yellow Orange", 0xFFAE42),
	YELLOW_ORANGE_COLOR_WHEEL	("Yellow Orange (Color Wheel)", 0xFF9505),
	YELLOW_SUNSHINE	 	 	 	("Yellow Sunshine", 0xFFF700),
	YINMN_BLUE	 	 	 		("YInMn Blue", 0x2E5090),
	ZAFFRE	 	 	 			("Zaffre", 0x14A8),
	ZOMP	 	 	 			("Zomp", 0x39A78E);
	
	private final String name;
	private final int hex;
	
	Colour (String name, int hex){
		this.name = name;
		this.hex = hex;
	}
	
	public String getFullName() {
		return name;
	}
	
	public int hex() {
		return hex;
	}
	
	public CharSequence rgb() {
		return "rgb(" +
	    ((hex & 0xFF0000) >> 16) + "," +
	    ((hex & 0xFF00) >> 8) + "," +
	    (hex & 0xFF) + ")";
	}
}